### ISSUE TITLE
exec /bin/sh: exec format error when deploying

### ISSUE THREAD

**Issue by ddakotac** [anatosun/plexamp-docker#2]
Hi,

Thanks for creating this docker image!

When I deploy it, the only things the logs show are "exec /bin/sh: exec format error".

The only thing I can think is that I am not understanding what the volume bindings should be? I currently have them pointed towards empty folders I created.

Any help appreciated, and apologies for my ignorance!

version: '3'
services:
  plexamp:
    container_name: example
    privileged: true
    network_mode: "host"
    image: ghcr.io/anatosun/plexamp:arm64v8
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - ./config:/home/user/Programs/plexamp/config/ # replace that with the appropriate host binding
      - /data/docker/plexamp/:/home/user/Programs/plexamp/docker/:rw
    environment:
        - PLEXAMP_CLAIM_TOKEN=claim-ywDa3Kuikwnyww9MmK3q# get your claim at https://www.plex.tv/claim/
        - PLEXAMP_PLAYER_NAME=example # replace this with your player name
    ports:
        - 32500:32500
        - 20000:20000
    restart: unless-stopped

**Comment by anatosun** [comment]
What's the hardware you're using?

**Comment by ddakotac** [comment]
Is this what you're looking for? It's basically a desktop PC running linux mint.

Linux 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

 description: Motherboard
       product: PRIME A320I-K
       vendor: ASUSTeK COMPUTER INC.
-memory
          description: System Memory
          physical id: 24
          slot: System board or motherboard
          size: 32GiB
*-cpu
          description: CPU
          product: AMD Athlon 3000G with Radeon Vega Graphics
          vendor: Advanced Micro Devices [AMD]
          physical id: 29
          bus info: cpu@0
          version: 23.24.1

**Comment by anatosun** [comment]
Then use the tag `amd64` which is more suitable for your CPU architecture.

**Comment by ddakotac** [comment]
Doh! That makes perfect sense. Thanks for taking the time.
